package assignment2;


/**
* assignment2/FileShareHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/assignment2/FileShare.idl
* Sunday, July 19, 2026 11:41:21 o'clock AM PDT
*/

abstract public class FileShareHelper
{
  private static String  _id = "IDL:assignment2/FileShare:1.0";

  public static void insert (org.omg.CORBA.Any a, assignment2.FileShare that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static assignment2.FileShare extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (assignment2.FileShareHelper.id (), "FileShare");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static assignment2.FileShare read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileShareStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, assignment2.FileShare value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static assignment2.FileShare narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof assignment2.FileShare)
      return (assignment2.FileShare)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      assignment2._FileShareStub stub = new assignment2._FileShareStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static assignment2.FileShare unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof assignment2.FileShare)
      return (assignment2.FileShare)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      assignment2._FileShareStub stub = new assignment2._FileShareStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
