package assignment2;


/**
* assignment2/FileShare.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/assignment2/FileShare.idl
* Sunday, July 19, 2026 11:41:21 o'clock AM PDT
*/

public interface FileShare extends FileShareOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileShare
