package assignment2;

/**
* assignment2/FileShareHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/assignment2/FileShare.idl
* Sunday, July 19, 2026 11:41:21 o'clock AM PDT
*/

public final class FileShareHolder implements org.omg.CORBA.portable.Streamable
{
  public assignment2.FileShare value = null;

  public FileShareHolder ()
  {
  }

  public FileShareHolder (assignment2.FileShare initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = assignment2.FileShareHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    assignment2.FileShareHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return assignment2.FileShareHelper.type ();
  }

}
