package assignment2;


/**
* assignment2/FileSharePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/assignment2/FileShare.idl
* Sunday, July 19, 2026 11:41:21 o'clock AM PDT
*/

public abstract class FileSharePOA extends org.omg.PortableServer.Servant
 implements assignment2.FileShareOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerFile", new java.lang.Integer (0));
    _methods.put ("updateFile", new java.lang.Integer (1));
    _methods.put ("searchFile", new java.lang.Integer (2));
    _methods.put ("downloadFile", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Register File
       case 0:  // assignment2/FileShare/registerFile
       {
         String ownerID = in.read_string ();
         String fileName = in.read_string ();
         boolean shared = in.read_boolean ();
         this.registerFile (ownerID, fileName, shared);
         out = $rh.createReply();
         break;
       }


  //Update File's share status
       case 1:  // assignment2/FileShare/updateFile
       {
         String ownerID = in.read_string ();
         String fileName = in.read_string ();
         boolean shared = in.read_boolean ();
         this.updateFile (ownerID, fileName, shared);
         out = $rh.createReply();
         break;
       }


  //Search whether files exists
       case 2:  // assignment2/FileShare/searchFile
       {
         String fileName = in.read_string ();
         boolean $result = false;
         $result = this.searchFile (fileName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  //Get owner of file to build socket and download
       case 3:  // assignment2/FileShare/downloadFile
       {
         String fileName = in.read_string ();
         assignment2.FileSharePackage.ClientInfo $result = null;
         $result = this.downloadFile (fileName);
         out = $rh.createReply();
         assignment2.FileSharePackage.ClientInfoHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:assignment2/FileShare:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileShare _this() 
  {
    return FileShareHelper.narrow(
    super._this_object());
  }

  public FileShare _this(org.omg.CORBA.ORB orb) 
  {
    return FileShareHelper.narrow(
    super._this_object(orb));
  }


} // class FileSharePOA
