package assignment2;


/**
* assignment2/FileShareOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/assignment2/FileShare.idl
* Sunday, July 19, 2026 11:41:21 o'clock AM PDT
*/

public interface FileShareOperations 
{

  //Register File
  void registerFile (String ownerID, String fileName, boolean shared);

  //Update File's share status
  void updateFile (String ownerID, String fileName, boolean shared);

  //Search whether files exists
  boolean searchFile (String fileName);

  //Get owner of file to build socket and download
  assignment2.FileSharePackage.ClientInfo downloadFile (String fileName);
} // interface FileShareOperations
