package assignment2.FileSharePackage;


/**
* assignment2/FileSharePackage/ClientInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/assignment2/FileShare.idl
* Sunday, July 19, 2026 11:41:21 o'clock AM PDT
*/

public final class ClientInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String ipAddress = null;
  public int port = (int)0;

  public ClientInfo ()
  {
  } // ctor

  public ClientInfo (String _ipAddress, int _port)
  {
    ipAddress = _ipAddress;
    port = _port;
  } // ctor

} // class ClientInfo
