package assignment2.FileSharePackage;

/**
* assignment2/FileSharePackage/ClientInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/assignment2/FileShare.idl
* Sunday, July 19, 2026 11:41:21 o'clock AM PDT
*/

public final class ClientInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public assignment2.FileSharePackage.ClientInfo value = null;

  public ClientInfoHolder ()
  {
  }

  public ClientInfoHolder (assignment2.FileSharePackage.ClientInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = assignment2.FileSharePackage.ClientInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    assignment2.FileSharePackage.ClientInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return assignment2.FileSharePackage.ClientInfoHelper.type ();
  }

}
